# Generated by Django 5.0.6 on 2024-06-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
